# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: MD Gen

on:
  push:
    branches:
      - master
      - 0.27

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 14.x
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - run: cd md_gen && npm ci && npm start
      - run: npm ci && npm run build
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Update MD
